[package]
name = "tea-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
base64 = "0.22.1"
wasm-bindgen = "0.2.92"

[package.metadata.wasm-pack.profile.release]
wasm-opt = false
